name: Autograding

on:
  push:
    branches:
    - '*'
    - '!badges'
    - '!feedback'

jobs:
  autograding:
    uses: UCLCOMP0061/workflows/.github/workflows/autograding.yml@main
    with:
      lab: zkp